name: ScheduleKun Test
on: push
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schedule_kun_backend
    services:
      postgresql:
        image: postgres:14
        ports:
          - 35432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1.0'
      - name: Install dependencies
        run: bundle install
      - name: seed_fu
        run: bundle exec rails db:seed_fu RAILS_ENV=test
      - name: run rspec
        run: bundle exec rspec
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: react eslint
        run: yarn lint
