name: ScheduleKun Test
on:
  - push
  - pull_request
env:
  DATABASE_HOST: 127.0.0.1
  DATABASE_PORT: 5432
  DATABASE_USERNAME: admin
  DATABASE_PASSWORD: password
  DATABASE_RAILS_MAX_THREADS: 5
  TEST_DATABASE: schedule-kun-test
  PRODUCTION_DATABASE: .
  DEVELOP_DATABASE: .
jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schedule_kun_backend
    services:
      postgresql:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1.0'
      - name: Install dependencies
        run: bundle install
      - name: db create
        run: bundle exec rails db:create RAILS_ENV=test
      - name: db migrate
        run: bundle exec rails db:migrate RAILS_ENV=test
      - name: seed_fu
        run: bundle exec rails db:seed_fu RAILS_ENV=test
      - name: run rspec
        run: bundle exec rspec
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schedule_kun_frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
